spring.application.name=pos_backend
spring.jpa.show-sql=true
hserver.port=8080
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL}

spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET_KEY}

# Frontend URL for CORS configuration
FRONTEND_URL=http://localhost:5173
